const studentData = [
    {
      Name : 'Sabbir',
      Roll : 04,
      Bn   : 57,
      En   : 77,
      Math   : 77,
      S   : 77,
      SS   : 77,
      Reli   : 77,
    }, {
        Name : 'Sabbir',
        Roll : 04,
        Bn   : 57,
        En   : 77,
        Math   : 77,
        S   : 77,
        SS   : 77,
        Reli   : 77,
      }, {
        Name : 'Sabbir',
        Roll : 04,
        Bn   : 57,
        En   : 77,
        Math   : 77,
        S   : 77,
        SS   : 77,
        Reli   : 77,
      }, {
        Name : 'Sabbir',
        Roll : 04,
        Bn   : 57,
        En   : 77,
        Math   : 77,
        S   : 77,
        SS   : 77,
        Reli   : 77,
      }, {
        Name : 'Sabbir',
        Roll : 04,
        Bn   : 57,
        En   : 77,
        Math   : 77,
        S   : 77,
        SS   : 77,
        Reli   : 77,
      }, {
        Name : 'Sabbir',
        Roll : 04,
        Bn   : 57,
        En   : 77,
        Math   : 77,
        S   : 77,
        SS   : 77,
        Reli   : 77,
      }, {
        Name : 'Sabbir',
        Roll : 04,
        Bn   : 57,
        En   : 77,
        Math   : 77,
        S   : 77,
        SS   : 77,
        Reli   : 77,
      }, {
        Name : 'Zonayed',
        Roll : 04,
        Bn   : 57,
        En   : 77,
        Math   : 77,
        S   : 77,
        SS   : 77,
        Reli   : 77,
      },
]